### ISSUE TITLE
Replace spaces in title with dashes in filename

### ISSUE THREAD

**Issue by mlncn** [trashfeed/save-as-heading#1]
Would be nice to have this as the default, or an option.  I'd like lower-casing enforced in the filename also, but dashes for spaces is my main hope.  Thanks for the Atom package!

**Comment by trashfeed** [comment]
Thanks for a good report!
Released a next version, and implemented new options.
This options can be used for replace in title to file name!

## New options
- Replace from
- Replace to
- Conversion filename

for details, please check the readme.
https://github.com/trashfeed/save-as-heading/blob/master/README.md#options

**Comment by mlncn** [comment]
Amazing!  Thank you!!

In addition to working beautifully as far as replacements in the file path, on my GNU/Linux system at least, it *seems* to have introduced a bug: a backslash rather than a forward slash in the path right at the start of the file name:

/home/mlncn/Projects/agaric/resources/raw-notes\2018-06-26-easily-figure-out-if-you-re-writing-valid-yaml.md

This means the above, rather than being in the raw-notes folder like it had been and should be, is an oddly named file with a backslash in it one directory up (a 'raw-notes\2018-etc.md' file in the resources directory in this case).

**Comment by trashfeed** [comment]
Thx! for the particular report.
I was able to reproduce the error you're seeing:sob:
Released the next version to fixed bug, please try again.

**Comment by mlncn** [comment]
Works great thank you!!!

**Comment by trashfeed** [comment]
No, thank YOU!!! YOU helped me a lot to close this issue.
